name: Release Workflow

on:
  release:
    types: [published]

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Get version and SHA256
        id: get_info
        run: |
          echo "VERSION=${{ github.event.release.name }}" >> $GITHUB_ENV
          ASSET_URL="https://github.com/ghall89/AutoDock/releases/download/v${{ github.event.release.tag_name }}/AutoDock.zip"
          echo "ASSET_URL=${ASSET_URL}" >> $GITHUB_ENV

          # Download the asset to calculate SHA256
          curl -L $ASSET_URL -o AutoDock.zip
          SHA256=$(sha256sum AutoDock.zip | awk '{ print $1 }')
          echo "SHA256=${SHA256}" >> $GITHUB_ENV

      - name: Update Homebrew Cask
        run: |
          PATH="Casks/autodock.rb"
          sed -i "s/version \".*\"/version \"${{ env.VERSION }}\"/" $PATH
          sed -i "s/sha256 \".*\"/sha256 \"${{ env.SHA256 }}\"/" $PATH

      - name: Commit changes
        run: |
          git config --local user.email "graham@ghall.dev"
          git config --local user.name "GitHub Action"
          git add $FORMULA_PATH
          git commit -m "Update AutoDock to version ${{ env.VERSION }}"

      - name: Push changes
        run: |
          git push origin main
